-- Migration 012: Add canonical URLs to all seeded resources
UPDATE resources SET url = 'https://education.github.com/pack'                WHERE name = 'GitHub Student Developer Pack' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.jstor.org'                             WHERE name = 'JSTOR'                          AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.webofscience.com'                      WHERE name = 'Web of Science'                 AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.scopus.com'                            WHERE name = 'Scopus'                         AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.proquest.com/products-services/dissertations'  WHERE name = 'ProQuest Dissertations' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://ieeexplore.ieee.org'                       WHERE name = 'IEEE Xplore'                    AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.foundry.com/products/nuke-family/nuke' WHERE name = 'Nuke Non-Commercial'           AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://pubmed.ncbi.nlm.nih.gov'                   WHERE name = 'PubMed Central'                AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://academic.lexisnexis.com'                   WHERE name = 'LexisNexis Academic'           AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.bloomberg.com/professional/solution/bloomberg-terminal' WHERE name = 'Bloomberg Terminal' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.autodesk.com/education/edu-software/overview' WHERE name = 'Autodesk Education Suite' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.jetbrains.com/community/education/'    WHERE name = 'JetBrains All Products Pack'   AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.adobe.com/creativecloud/buy/students.html' WHERE name = 'Adobe Creative Cloud All Apps' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.figma.com/education/'                  WHERE name = 'Figma Professional'           AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.canva.com/education/'                  WHERE name = 'Canva Pro'                     AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://unity.com/education'                       WHERE name = 'Unity Pro'                     AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://education.github.com/pack'                 WHERE name = 'GitHub Student Developer Pack' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.microsoft.com/en-us/education/products/office' WHERE name = 'Microsoft 365 Education' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://aws.amazon.com/education/awseducate/'      WHERE name = 'AWS Educate'                  AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://azure.microsoft.com/en-us/free/students/' WHERE name = 'Microsoft Azure'              AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://cloud.google.com/edu/students'             WHERE name = 'Google Cloud Platform'        AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.mongodb.com/students'                  WHERE name = 'MongoDB Atlas'                AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.digitalocean.com/github-students'      WHERE name = 'DigitalOcean'                 AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.heroku.com'                            WHERE name = 'Heroku'                       AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.cloudflare.com'                        WHERE name = 'Cloudflare'                   AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://one.google.com/about/ai-premium'           WHERE name = 'Google One AI Premium'        AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.notion.so/students'                    WHERE name = 'Notion AI'                    AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://perplexity.ai'                             WHERE name = 'Perplexity Pro'               AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.grammarly.com'                         WHERE name = 'Grammarly Premium'            AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://julius.ai'                                 WHERE name = 'Julius AI'                    AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://otter.ai'                                  WHERE name = 'Otter.ai Pro'                 AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.humata.ai'                             WHERE name = 'Humata'                       AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.wolframalpha.com'                      WHERE name = 'Wolfram Alpha Pro'            AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://airtable.com'                              WHERE name = 'Airtable Pro'                 AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://slack.com'                                 WHERE name = 'Slack Standard'              AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://zoom.us/education'                         WHERE name = 'Zoom Pro'                     AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.datacamp.com'                          WHERE name = 'DataCamp Premium'             AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://miro.com/education/'                       WHERE name = 'Miro Team'                    AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://lucid.app/education'                       WHERE name = 'Lucidchart Education'         AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.invisionapp.com'                       WHERE name = 'InVision'                     AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://framer.com'                                WHERE name = 'Framer'                       AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.sketch.com/education/'                 WHERE name = 'Sketch'                       AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.adobe.com/products/substance3d/substance-painter-and-designer.html' WHERE name = 'Substance Painter/Designer' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.mailchimp.com'                         WHERE name = 'Mailchimp Pro'                AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.typeform.com'                          WHERE name = 'Typeform Pro'                 AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://requestly.com'                             WHERE name = 'Requestly'                    AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.linkedin.com/learning/'                WHERE name = 'LinkedIn Premium'             AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://open.spotify.com/us/students'              WHERE name = 'Spotify Premium'             AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.amazon.com/joinstudentprograms'        WHERE name = 'Amazon Prime Student'         AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://discord.com/nitro'                         WHERE name = 'Discord Nitro'                AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.opm.gov/healthcare-insurance/healthcare/plan-information/' WHERE name = 'Government Training Resources' AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.usa.gov/government-employee-discounts' WHERE name = 'Federal Employee Discounts'   AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.blender.org'                           WHERE name = 'Blender'                      AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://krita.org'                                 WHERE name = 'Krita'                        AND (url IS NULL OR url = '');
UPDATE resources SET url = 'https://www.blackmagicdesign.com/products/davinciresolve' WHERE name = 'DaVinci Resolve Studio' AND (url IS NULL OR url = '');
