-- Migration 054: EOB statements table (one row per uploaded PDF statement)
CREATE TABLE IF NOT EXISTS med_eob_statements (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  insurer               TEXT NOT NULL DEFAULT 'MHBP',
  plan_name             TEXT,
  group_name            TEXT,
  member_id             TEXT,
  group_number          TEXT,
  member_name           TEXT,
  statement_date        DATE NOT NULL,
  period_start          DATE,
  period_end            DATE,
  amount_billed         REAL,
  allowed_amount        REAL,
  pending_not_payable   REAL,
  deductible_applied    REAL,
  copay_total           REAL,
  coinsurance_total     REAL,
  plan_paid_total       REAL,
  your_share_total      REAL,
  amount_saved          REAL,
  healthfund_applied    REAL,
  deductible_annual     REAL,
  deductible_used       REAL,
  deductible_remaining  REAL,
  oop_max_annual        REAL,
  oop_used              REAL,
  oop_remaining         REAL,
  healthfund_total      REAL,
  healthfund_used       REAL,
  healthfund_remaining  REAL,
  source_filename       TEXT,
  created_at            DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(statement_date, member_id)
);
CREATE INDEX IF NOT EXISTS idx_eob_stmt_date ON med_eob_statements(statement_date DESC);
