-- Migration 059: Expand category rules with more merchants and DFAS/federal patterns
-- All patterns use LIKE syntax (%=wildcard). First match wins (sort_order).
-- Only inserts where pattern doesn't already exist.
INSERT OR IGNORE INTO import_category_rules (pattern, category, sort_order) VALUES
  -- Income (federal/military specific)
  ('%DFAS%',            'Income',         1),
  ('%FEDERAL SALARY%',  'Income',         2),
  ('%OPM%',             'Income',         3),
  ('%USAJOBS%',         'Income',         4),
  ('%REFUND%',          'Income',         6),
  ('%TAX REFUND%',      'Income',         7),
  -- Groceries
  ('%SAM%S CLUB%',      'Groceries',     16),
  ('%SAMS CLUB%',       'Groceries',     17),
  ('%TRADER JOE%',      'Groceries',     18),
  ('%FOOD LION%',       'Groceries',     19),
  ('%INGLES%',          'Groceries',     20),
  ('%SPROUTS%',         'Groceries',     21),
  ('%WINN DIXIE%',      'Groceries',     22),
  ('%FRESH MARKET%',    'Groceries',     23),
  ('%HARRIS TEETER%',   'Groceries',     24),
  ('%PIGGLY%',          'Groceries',     25),
  ('%DOLLAR GENERAL%',  'Groceries',     26),
  ('%FAMILY DOLLAR%',   'Groceries',     27),
  -- Dining
  ('%PANERA%',          'Dining',        56),
  ('%DOMINO%',          'Dining',        57),
  ('%PAPA JOHN%',       'Dining',        58),
  ('%PIZZA%',           'Dining',        59),
  ('%SUBWAY%',          'Dining',        60),
  ('%WENDY%',           'Dining',        61),
  ('%BURGER KING%',     'Dining',        62),
  ('%TACO BELL%',       'Dining',        63),
  ('%DUNKIN%',          'Dining',        64),
  ('%MOE%S%',           'Dining',        65),
  ('%WHATABURGER%',     'Dining',        66),
  ('%CRACKER BARREL%',  'Dining',        67),
  ('%OLIVE GARDEN%',    'Dining',        68),
  ('%CHILIS%',          'Dining',        69),
  ('%APPLEBEE%',        'Dining',        70),
  ('%WAFFLE HOUSE%',    'Dining',        71),
  ('%IHOP%',            'Dining',        72),
  ('%DENNY%',           'Dining',        73),
  -- Transportation / Gas
  ('%MARATHON%',        'Transportation',47),
  ('%CIRCLE K%',        'Transportation',48),
  ('%PILOT%',           'Transportation',49),
  ('%LOVE%S%',          'Transportation',50),
  ('%SPEEDWAY%',        'Transportation',51),
  ('%MURPHY%',          'Transportation',52),
  ('%SUNOCO%',          'Transportation',53),
  ('%VALERO%',          'Transportation',54),
  ('%KWIK TRIP%',       'Transportation',55),
  ('%PARKING%',         'Transportation',56),
  ('%CAR WASH%',        'Transportation',57),
  ('%AUTOZONE%',        'Transportation',58),
  ('%O%REILLY AUTO%',   'Transportation',59),
  ('%ADVANCE AUTO%',    'Transportation',60),
  -- Utilities / Telecom
  ('%ALABAMAPOWER%',    'Utilities',     77),
  ('%ALABAMA POWER%',   'Utilities',     78),
  ('%ALAGASCO%',        'Utilities',     79),
  ('%SPIRE%',           'Utilities',     80),
  ('%XFINITY%',         'Utilities',     81),
  ('%SPECTRUM%',        'Utilities',     82),
  ('%COX COMM%',        'Utilities',     83),
  ('%DISH %',           'Utilities',     84),
  ('%DIRECTV%',         'Utilities',     85),
  -- Subscriptions / Streaming
  ('%DISNEY%',          'Subscriptions', 35),
  ('%HBO%',             'Subscriptions', 36),
  ('%YOUTUBE%',         'Subscriptions', 37),
  ('%AMAZON PRIME%',    'Subscriptions', 38),
  ('%MICROSOFT%',       'Subscriptions', 39),
  ('%DROPBOX%',         'Subscriptions', 40),
  ('%ADOBE%',           'Subscriptions', 41),
  ('%AUDIBLE%',         'Subscriptions', 42),
  ('%KINDLE%',          'Subscriptions', 43),
  -- Healthcare
  ('%LABCORP%',         'Healthcare',    86),
  ('%QUEST DIAG%',      'Healthcare',    87),
  ('%URGENT CARE%',     'Healthcare',    88),
  ('%DENTAL%',          'Healthcare',    89),
  ('%VISION%',          'Healthcare',    90),
  ('%OPTOMETRIST%',     'Healthcare',    91),
  ('%AETNA%',           'Healthcare',    92),
  ('%BCBS%',            'Healthcare',    93),
  -- Insurance (non-health)
  ('%ALLSTATE%',        'Insurance',     93),
  ('%PROGRESSIVE%',     'Insurance',     94),
  ('%NATIONWIDE%',      'Insurance',     95),
  ('%USAA INS%',        'Insurance',     96),
  -- Shopping
  ('%EBAY%',            'Shopping',      22),
  ('%ETSY%',            'Shopping',      23),
  ('%BEST BUY%',        'Shopping',      24),
  ('%HOME DEPOT%',      'Shopping',      25),
  ('%LOWE%S%',          'Shopping',      26),
  ('%IKEA%',            'Shopping',      27),
  ('%MARSHALLS%',       'Shopping',      28),
  ('%TJ MAXX%',         'Shopping',      29),
  ('%KOHLS%',           'Shopping',      30),
  ('%MACYS%',           'Shopping',      31),
  ('%OLD NAVY%',        'Shopping',      32),
  ('%GAP%',             'Shopping',      33),
  -- Taxes
  ('%IRS%',             'Taxes',        105),
  ('%AL DEPT REV%',     'Taxes',        106),
  ('%STATE TAX%',       'Taxes',        107),
  -- Travel
  ('%DELTA AIR%',       'Travel',       108),
  ('%SOUTHWEST AIR%',   'Travel',       109),
  ('%UNITED AIR%',      'Travel',       110),
  ('%AMERICAN AIR%',    'Travel',       111),
  ('%MARRIOTT%',        'Travel',       112),
  ('%HILTON%',          'Travel',       113),
  ('%HYATT%',           'Travel',       114),
  ('%AIRBNB%',          'Travel',       115),
  ('%HOTEL%',           'Travel',       116),
  ('%EXPEDIA%',         'Travel',       117),
  -- Education
  ('%TUITION%',         'Education',    118),
  ('%UNIVERSITY%',      'Education',    119),
  ('%COLLEGE%',         'Education',    120),
  ('%SCHOOL%',          'Education',    121),
  ('%UDEMY%',           'Education',    122),
  ('%COURSERA%',        'Education',    123),
  -- Cash / ATM
  ('%ATM%',             'Other',        200),
  ('%CASH%',            'Other',        201);
