'use strict';
/**
 * features/notifications/routes.js
 *
 * In-app notification feed. Notifications are generated by backend events
 * (expiring certs, follow-ups due, low stock) and surfaced in the nav bell icon.
 *
 * GET  /         — list unread notifications
 * PUT  /:id/read — mark a notification read
 * PUT  /read-all — mark all notifications read
 * DELETE /:id    — dismiss a notification
 *
 * Notifications are created by other modules (not this one) by inserting
 * into the notifications table directly.
 * All routes are public (reads) or auth-required (writes).
 */
const express = require('express');
const router  = express.Router();
const db      = require('../../db/db');
const { requireAuth } = require('../auth/middleware');

function timeAgo(dateStr) {
  if (!dateStr) return '';
  const diff = (Date.now() - new Date(dateStr).getTime()) / 1000;
  if (diff < 60)   return 'just now';
  if (diff < 3600) return Math.floor(diff/60) + 'm ago';
  if (diff < 86400)return Math.floor(diff/3600) + 'h ago';
  return Math.floor(diff/86400) + 'd ago';
}

// Regenerate notifications from live data (called on read)
function generateNotifications() {
  const now  = new Date().toISOString().slice(0,10);
  const soon30 = new Date(Date.now() + 30*24*60*60*1000).toISOString().slice(0,10);
  const soon60 = new Date(Date.now() + 60*24*60*60*1000).toISOString().slice(0,10);
  const soon90 = new Date(Date.now() + 90*24*60*60*1000).toISOString().slice(0,10);
  const year = new Date().getFullYear().toString();

  const ins = (type, severity, title, body, module, entity_type) =>
    db.prepare(`INSERT INTO notifications (type,severity,title,body,module,entity_type) VALUES (?,?,?,?,?,?)`)
      .run(type, severity, title, body, module, entity_type||null);

  // Clear auto-generated
  db.prepare("DELETE FROM notifications WHERE type IN ('expiry','hsa_pool','follow_up','receipt','todo','cert','vehicle','gift_card','document')").run();

  // 1. Expired inventory items
  const invExpired = db.prepare(`SELECT COUNT(*) as n FROM items i JOIN item_hw_details hw ON hw.item_id=i.id WHERE i.is_active=1 AND i.is_archived=0 AND hw.expiration_date < ?`).get(now);
  if (invExpired.n > 0) ins('expiry','overdue',`${invExpired.n} expired inventory item${invExpired.n>1?'s':''}`, 'Remove expired items from your inventory','inventory','inventory');

  const invExpiring = db.prepare(`SELECT COUNT(*) as n FROM items i JOIN item_hw_details hw ON hw.item_id=i.id WHERE i.is_active=1 AND i.is_archived=0 AND hw.expiration_date >= ? AND hw.expiration_date <= ?`).get(now, soon30);
  if (invExpiring.n > 0) ins('expiry','pending',`${invExpiring.n} inventory item${invExpiring.n>1?'s':''} expiring soon`,'Items expire within 30 days','inventory','inventory');

  // 2. HSA
  const missing = db.prepare(`SELECT COUNT(*) as n FROM hsa_payments WHERE strftime('%Y',date)=? AND receipt_saved=0 AND hsa_eligible=1`).get(year);
  if (missing.n > 0) ins('receipt','pending',`${missing.n} HSA expense${missing.n>1?'s':''} missing receipt`,'Add receipts to qualify for reimbursement','finance','hsa');

  const pool = db.prepare(`SELECT COALESCE(SUM(CASE WHEN hsa_eligible=1 AND reimbursed=0 THEN you_paid ELSE 0 END),0) as p FROM hsa_payments WHERE strftime('%Y',date)=?`).get(year);
  if ((pool.p||0) > 200) ins('hsa_pool','info',`$${Math.round(pool.p).toLocaleString()} unreimbursed HSA pool`,'Eligible expenses not yet reimbursed this year','finance','hsa');

  // 3. Daily log follow-ups
  const fuOverdue = db.prepare(`SELECT COUNT(*) as n FROM daily_log WHERE follow_up_needed=1 AND follow_up_date < ?`).get(now);
  if (fuOverdue.n > 0) ins('follow_up','overdue',`${fuOverdue.n} overdue follow-up${fuOverdue.n>1?'s':''}`, 'Past-due log entries need follow-up','daily_log','daily_log');

  const fuPending = db.prepare(`SELECT COUNT(*) as n FROM daily_log WHERE follow_up_needed=1 AND (follow_up_date IS NULL OR follow_up_date >= ?)`).get(now);
  if (fuPending.n > 0) ins('follow_up','pending',`${fuPending.n} follow-up${fuPending.n>1?'s':''} pending`,'Log entries awaiting follow-up','daily_log','daily_log');

  // 4. Overdue todos
  const todOverdue = db.prepare(`SELECT COUNT(*) as n FROM todos WHERE status IN ('open','in_progress') AND due_date < ?`).get(now);
  if (todOverdue.n > 0) ins('todo','overdue',`${todOverdue.n} overdue to-do${todOverdue.n>1?'s':''}`,`Tasks past their due date`,'todos','todos');

  const todUrgent = db.prepare(`SELECT COUNT(*) as n FROM todos WHERE status IN ('open','in_progress') AND priority='urgent'`).get();
  if (todUrgent.n > 0) ins('todo','pending',`${todUrgent.n} urgent to-do${todUrgent.n>1?'s':''}`,`High priority tasks need attention`,'todos','todos');

  // 5. Career certifications (safe — table may not exist yet)
  try {
    const certExpired = db.prepare(`SELECT COUNT(*) as n FROM career_certifications WHERE expiry_date IS NOT NULL AND expiry_date < ? AND status != 'Expired'`).get(now);
    if (certExpired.n > 0) ins('cert','overdue',`${certExpired.n} certification${certExpired.n>1?'s':''} expired`,'Renew expired certifications','career','certification');

    const certSoon = db.prepare(`SELECT COUNT(*) as n FROM career_certifications WHERE expiry_date IS NOT NULL AND expiry_date >= ? AND expiry_date <= ? AND status != 'Expired'`).get(now, soon60);
    if (certSoon.n > 0) ins('cert','pending',`${certSoon.n} certification${certSoon.n>1?'s':''} expiring within 60 days`,'Schedule renewals soon','career','certification');
  } catch(e) {}

  // 6. Vehicle registration / inspection (safe)
  try {
    const vRegExpired = db.prepare(`SELECT COUNT(*) as n FROM vehicles WHERE is_active=1 AND registration_expires IS NOT NULL AND registration_expires < ?`).get(now);
    if (vRegExpired.n > 0) ins('vehicle','overdue',`${vRegExpired.n} vehicle registration${vRegExpired.n>1?'s':''} expired`,'Renew vehicle registration immediately','property','vehicle');

    const vRegSoon = db.prepare(`SELECT COUNT(*) as n FROM vehicles WHERE is_active=1 AND registration_expires IS NOT NULL AND registration_expires >= ? AND registration_expires <= ?`).get(now, soon30);
    if (vRegSoon.n > 0) ins('vehicle','pending',`${vRegSoon.n} vehicle registration${vRegSoon.n>1?'s':''} expiring soon`,'Registration due within 30 days','property','vehicle');

    const vInspExp = db.prepare(`SELECT COUNT(*) as n FROM vehicles WHERE is_active=1 AND inspection_expires IS NOT NULL AND inspection_expires < ?`).get(now);
    if (vInspExp.n > 0) ins('vehicle','overdue',`${vInspExp.n} vehicle inspection${vInspExp.n>1?'s':''} expired`,'Schedule inspection immediately','property','vehicle');

    const vInspSoon = db.prepare(`SELECT COUNT(*) as n FROM vehicles WHERE is_active=1 AND inspection_expires IS NOT NULL AND inspection_expires >= ? AND inspection_expires <= ?`).get(now, soon30);
    if (vInspSoon.n > 0) ins('vehicle','pending',`${vInspSoon.n} vehicle inspection${vInspSoon.n>1?'s':''} due soon`,'Inspection due within 30 days','property','vehicle');
  } catch(e) {}

  // 7. Gift cards expiring (safe)
  try {
    const gcExp = db.prepare(`SELECT COUNT(*) as n FROM gift_cards WHERE is_active=1 AND expiry_date IS NOT NULL AND expiry_date >= ? AND expiry_date <= ?`).get(now, soon30);
    if (gcExp.n > 0) ins('gift_card','pending',`${gcExp.n} gift card${gcExp.n>1?'s':''} expiring soon`,'Use or check balances before they expire','finance','gift_card');

    const gcExpired = db.prepare(`SELECT COUNT(*) as n FROM gift_cards WHERE is_active=1 AND expiry_date IS NOT NULL AND expiry_date < ?`).get(now);
    if (gcExpired.n > 0) ins('gift_card','overdue',`${gcExpired.n} gift card${gcExpired.n>1?'s':''} expired`,'Remove expired gift cards','finance','gift_card');
  } catch(e) {}

  // 8. Documents expiring (safe)
  try {
    const docExpired = db.prepare(`SELECT COUNT(*) as n FROM documents WHERE is_active=1 AND expiry_date IS NOT NULL AND expiry_date < ?`).get(now);
    if (docExpired.n > 0) ins('document','overdue',`${docExpired.n} document${docExpired.n>1?'s':''} expired`,'Review and renew expired documents','documents','document');

    const docSoon = db.prepare(`SELECT COUNT(*) as n FROM documents WHERE is_active=1 AND expiry_date IS NOT NULL AND expiry_date >= ? AND expiry_date <= ?`).get(now, soon90);
    if (docSoon.n > 0) ins('document','pending',`${docSoon.n} document${docSoon.n>1?'s':''} expiring within 90 days`,'Review documents before they expire','documents','document');
  } catch(e) {}
}

// GET /api/v1/notifications
router.get('/', (req, res) => {
  try {
    generateNotifications();
    const rows = db.prepare(`
      SELECT * FROM notifications
      ORDER BY
        CASE severity WHEN 'overdue' THEN 1 WHEN 'pending' THEN 2 ELSE 3 END,
        created_at DESC
      LIMIT 50
    `).all();
    res.json(rows.map(r => ({ ...r, time_ago: timeAgo(r.created_at) })));
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// GET /api/v1/notifications/unread-count
router.get('/unread-count', (req, res) => {
  try {
    generateNotifications();
    const { n } = db.prepare("SELECT COUNT(*) as n FROM notifications WHERE is_read=0").get();
    res.json({ count: n });
  } catch(e) { res.status(500).json({ count: 0 }); }
});

// ── All routes below require authentication ──────────────────
router.use(requireAuth);

// PATCH /api/v1/notifications/:id/read
router.patch('/:id/read', (req, res) => {
  try {
    db.prepare("UPDATE notifications SET is_read=1 WHERE id=?").run(req.params.id);
    res.json({ ok: true });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// PATCH /api/v1/notifications/read-all
router.patch('/read-all', (req, res) => {
  try {
    db.prepare("UPDATE notifications SET is_read=1").run();
    res.json({ ok: true });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;
